import {ISite} from "./DetailAndRiskTypes";

export const DetailsAndRisksSite: ISite = {
    address: "",
    landlordGroup: "",
    landlordOther: "",
    contractCurrency: "",
    indexation: "",
    breakOption: "",
    extensionOption: "",
    maintenance: "",
    incentives: "",
    SecurityDeposit: "",
    SecurityDepositOther: "",
    deniedPartyScreening: false,
    gogreenMinStandards: false,
    otherInfo: "",
    makeGoodValue: "",
    makeGoodComment: "",
    otherOneOffValue: "",
    otherOneOffComment: "",
    dilapidationsValue: "",
    dilapidationsComment: "",
    LHIValue: "",
    LHIComment: "",
    otherCapexValue: "",
    otherCapexComment: "",
    totalRentValue: "",
    totalRentComments: "",
    otherOngoingValue: "",
    otherOngoingComments: "",
    depreciationPerYearValue: "",
    depreciationPerYearComment: "",
    depreciationPerMonthValue: "",
    depreciationPerMonthComment: "",
}